# permissions for end users to edit injectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: injector-operator
    app.kubernetes.io/managed-by: kustomize
  name: injector-editor-role
rules:
- apiGroups:
  - injector.example.com
  resources:
  - injectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - injector.example.com
  resources:
  - injectors/status
  verbs:
  - get
