---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - injector.example.com
  resources:
  - injectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - injector.example.com
  resources:
  - injectors/finalizers
  verbs:
  - update
- apiGroups:
  - injector.example.com
  resources:
  - injectors/status
  verbs:
  - get
  - patch
  - update
