apiVersion: injector.example.com/v1alpha1
kind: Injector
metadata:
  labels:
    app.kubernetes.io/name: injector-operator
    app.kubernetes.io/managed-by: kustomize
  name: injector-sample
spec:
  # TODO(user): Add fields here
